-- Opprett skjema
CREATE SCHEMA portreg;

-- Installer PostgreSQL's Earthdistance Module
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;

-- Opprett tabell
CREATE TABLE portreg.Port (
LOCODE VARCHAR(255) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
LAT decimal,
LON decimal);

CREATE TABLE portreg.port_sync_log (
ALPHA2_COUNTRY_CODE VARCHAR(2) PRIMARY KEY ,
OUTCOME VARCHAR(7) NOT NULL,
SYNCHRONIZATION_DATE TIMESTAMP NOT NULL,
CHECK (OUTCOME IN ('SUCCESS', 'FAILED'))
);